# Generated by Django 3.1 on 2020-08-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('matches_played', models.IntegerField(blank=True, null=True)),
                ('matches_won', models.IntegerField(blank=True, null=True)),
                ('matches_loose', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='matches_loose',
        ),
        migrations.RemoveField(
            model_name='team',
            name='matches_played',
        ),
        migrations.RemoveField(
            model_name='team',
            name='matches_won',
        ),
    ]
