# Generated by Django 3.1 on 2020-08-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['country_name']},
        ),
        migrations.RenameField(
            model_name='country',
            old_name='cname',
            new_name='country_name',
        ),
    ]
