# Generated by Django 3.1 on 2020-08-25 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200825_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('matches_played', models.IntegerField(blank=True, null=True)),
                ('matches_won', models.IntegerField(blank=True, null=True)),
                ('matches_loose', models.IntegerField(blank=True, null=True)),
                ('man_of_the_match', models.CharField(blank=True, max_length=100, null=True)),
                ('bowler_of_the_match', models.CharField(blank=True, max_length=100, null=True)),
                ('best_fielder', models.CharField(blank=True, max_length=100, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
        ),
        migrations.DeleteModel(
            name='Matches',
        ),
    ]
