# Generated by Django 3.1 on 2020-08-27 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200826_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchscorecard',
            name='scores',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.playerscore'),
        ),
    ]
