# Generated by Django 3.1 on 2020-08-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200825_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='matches_loose',
            new_name='match_no',
        ),
        migrations.RemoveField(
            model_name='match',
            name='matches_played',
        ),
        migrations.RemoveField(
            model_name='match',
            name='matches_won',
        ),
        migrations.AddField(
            model_name='match',
            name='looser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
