# Generated by Django 3.1 on 2020-09-01 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_matchscorecard_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchscorecard',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.team'),
        ),
    ]
