# Generated by Django 3.1 on 2020-08-25 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200825_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='man_of_the_match',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.team'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.country'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='matches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.match'),
        ),
    ]
