# Generated by Django 3.1 on 2020-08-25 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200825_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='best_fielder',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_fielder', to='api.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='bowler_of_the_match',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bowler_of_the_match', to='api.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='man_of_the_match',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='man_of_the_match', to='api.player'),
        ),
    ]
