# Generated by Django 3.1 on 2020-08-25 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200825_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='matches',
        ),
    ]
