# Generated by Django 3.1 on 2020-08-25 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_venue_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue', to='api.venue'),
        ),
    ]
