# Generated by Django 3.1 on 2020-08-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_match_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchScorecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.CharField(blank=True, choices=[('test match', 'test match'), ('one day international', 'one day international'), ('twenty 20 world cup', 'twenty 20 world cup')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
