# Generated by Django 3.1 on 2020-08-25 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200825_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchscorecard',
            name='team',
        ),
        migrations.AddField(
            model_name='matchscorecard',
            name='venue',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.venue'),
        ),
    ]
