# Generated by Django 3.1 on 2020-08-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200825_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='cname',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
