# Generated by Django 3.1 on 2020-08-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200825_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchscorecard',
            name='venue',
        ),
        migrations.AddField(
            model_name='matchscorecard',
            name='venue',
            field=models.ManyToManyField(blank=True, null=True, to='api.Venue'),
        ),
    ]
