# Generated by Django 3.1 on 2020-08-25 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200825_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchscorecard',
            name='venue',
        ),
        migrations.AddField(
            model_name='matchscorecard',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.venue'),
        ),
    ]
