# Generated by Django 3.1 on 2020-08-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200825_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['cname']},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['country']},
        ),
        migrations.AddField(
            model_name='matchscorecard',
            name='bounce',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchscorecard',
            name='four',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchscorecard',
            name='six',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchscorecard',
            name='wide',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='playerscore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
