# Generated by Django 3.1 on 2020-08-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200826_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(default='NULL', max_length=100, primary_key=True, serialize=False),
        ),
    ]
